name: sample

on:
 push: 
  branches: [feature/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: testing
      run: |
        echo ${{github.run_number}}
        echo ${{github.run_attempt}}