name: "release to main automatic merging and tagging"

on:
 workflow_dispatch:

jobs:
  auto-pr-merge-tagging:
    name: "merging and tagging"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: create pull request
        id: demo
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: "An automatically created PR!"
      
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo.outputs.number }}
	    
      - name: Merge Pull Request
    	  uses: juliangruber/merge-pull-request-action@v1
    	  with:
      	  github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo.outputs.number }}
