name: dev-qa

on:
  workflow_dispatch:

jobs:
  release-test:

    runs-on: ubuntu-latest

    steps:
    - run: |
        x=$(echo ${{ github.ref_name }} | awk -F 'release' '{print $2}')
        echo $x
