name: dev-qa

on:
  workflow_dispatch:

jobs:
  release-test:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "x=$(echo ${{ github.ref_name }} | awk -F 'release_' '{print $2}')" >> $GITHUB_ENV
        echo $x
    - name: testing 
      run: echo $x
