name: rollback

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Rollback version'  
       

jobs:
  rollback:
    name: rollback to previous version
    runs-on: ubuntu-latest

    steps:

    - if: ${{ github.event.inputs.version != '' }}
      name: rollback to given input version
      run: echo ${{ github.event.inputs.version }}

    - if: ${{ github.event.inputs.version == '' }}
      name: rollback to previous version
      run: echo "rollback to previous version"
       
