name: sample

on:
 push: 
  branches: [feature/*]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: testing
      run: |
        VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo $VERSION