name: sample

on:
 push: 
  branches: [feature/*]

jobs:
  get-version:
    name: getting artifact version
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get Version
      uses: entimaniac/read-pom-version-action@1.0.0
      id: getVersion
    - name: Print the version
      run: echo "The version we just got is ${{ steps.getVersion.outputs.version }}"